<?xml version="1.0" encoding="utf-8"?><Database Name="EMPLOYEE_DATABSE_BIG" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-OFQGFH7Q\SQL_SRV_TRANTOR;Initial Catalog=EMPLOYEE_DATABSE_BIG;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EMPLOYEE_DATABSE_BIGConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.register_student" Member="register_students">
    <Type Name="register_student">
      <Column Name="rollno" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="emailid" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>